### PR TITLE
Feature/code obfuscation

### PR DESCRIPTION
**Pull request by kjoneandrei**

### CODE REVIEW

**Comment by nickskull** [comment]
It looks ok to me, just one question regarding de-obfuscation - eg. I think we need to expose the mapping file somehow (at least on Bitrise) so that we have a chance at deobfuscating crash reports, otherwise they will be all rendered pointless.

**Comment by kjoneandrei** [comment]
true, how will we expose that file? the file gets created when the obfuscate command gets ran

**Comment by nickskull** [comment]
See https://devcenter.bitrise.io/builds/build-artifacts-online/

**Comment by kjoneandrei** [comment]
Found out the project needs to be signed before obfuscation to assure that it compiles, since the obfuscation step will try to build the project

**Pull request merged**
